Feature vpc
sunilsunderrajdev/ydm_repo1 pull request #24
Opened 2023-12-06 23:03 UTC by sunilsunderrajdev

VPC Task

2023-12-06 23:23 UTC, geoffrey1330 requested changes

2023-12-06 23:23 UTC, geoffrey1330 commented on .github/workflows/main..yml
> +#        run: terraform apply -destroy
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on ec2.tf
> +    public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGYsZQumFVfIvHlIS/UppkAhfu5N9vZ0kMFcZEviH3TXEgXZ5pChUPTWjcEhViq5MJhJS4UfvBNluPd3K8UGnnduaeRoZ9yURYp2Sy39EZvonVbj0zoi3SxpmKHif9u4f/Az8WxalBKRn8c
could you please remove the hardcoded key and associate a keypair to this ec2 instance.

2023-12-06 23:23 UTC, geoffrey1330 commented on ec2.tf
> +}
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on main.tf
> +}
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on ec2.tf
> +    public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmkm4M7pgDMhb8z7GKFl2SDBwoe8AiMaJ19H1y+L2s7hNCqhnfkoykv9vqBBdHkCHOIfHd7Zz0B3qIsI4RrOSanXDWsoV4WBOfIXvIAbVOk3BIA4bDQoh3OfPawIrvYceNPun05F106vqho
could you please remove the hardcoded key and associate a keypair to this ec2 instance.

2023-12-06 23:23 UTC, geoffrey1330 commented on network.tf
> + count      = length(["10.0.3.0/24","10.0.4.0/24"])
declare this cidr in a var or terraform locals and then make i reference to it here.

2023-12-06 23:23 UTC, geoffrey1330 commented on network.tf
> + cidr_block = element(["10.0.1.0/24","10.0.2.0/24"], count.index)
declare this cidr in a var or terraform locals and then make i reference to it here

2023-12-06 23:23 UTC, geoffrey1330 commented on network.tf
> +}
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on outputs.tf
> +#}
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on providers.tf
> +}
could you please add a newline at the end of file.

2023-12-06 23:23 UTC, geoffrey1330 commented on variables.tf
> +}
could you please add a newline at the end of file.

2023-12-07 23:10 UTC, closed without merging

2023-12-07 23:10 UTC, sunilsunderrajdev commented
Changes requested